# Generated by Django 4.2.30 on 2026-06-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "order",
                "verbose_name_plural": "orders",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["id"],
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.AlterModelOptions(
            name="promocode",
            options={
                "ordering": ["code"],
                "verbose_name": "promo code",
                "verbose_name_plural": "promo codes",
            },
        ),
        migrations.AlterModelOptions(
            name="promocodeusage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "promo code usage",
                "verbose_name_plural": "promo code usages",
            },
        ),
        migrations.RemoveConstraint(
            model_name="order",
            name="order_discount_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="order_item_discount_gte_0",
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(("discount__gte", 0), ("discount__lte", 1)),
                name="order_discount_between_0_and_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("discount__gte", 0), ("discount__lte", 1)),
                name="order_item_discount_between_0_and_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="promocode",
            constraint=models.CheckConstraint(
                check=models.Q(("max_uses__gt", 0)), name="promo_max_uses_gt_0"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="shop_order_user_id_f8b1c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["promo_code", "-created_at"],
                name="shop_order_promo_c_f9cda2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "product"], name="shop_orderi_order_i_d3fcce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_promo_excluded"],
                name="shop_produc_categor_c3bc67_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(
                fields=["is_active", "valid_until"],
                name="shop_promoc_is_acti_4142a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promocodeusage",
            index=models.Index(
                fields=["promo_code", "-created_at"],
                name="shop_promoc_promo_c_8ad991_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promocodeusage",
            index=models.Index(
                fields=["user", "-created_at"], name="shop_promoc_user_id_0c508f_idx"
            ),
        ),
    ]
